# Generated by Django 5.1.6 on 2025-03-01 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_alter_orderitem_options_alter_discount_amount_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='discounts',
            new_name='discount',
        ),
    ]
